//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorKeeperRoom.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoorKeeperRoom_DBConnection : DbContext
    {
        public DoorKeeperRoom_DBConnection()
            : base("name=DoorKeeperRoom_DBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<key_handing> key_handing { get; set; }
        public virtual DbSet<keys> keys { get; set; }
        public virtual DbSet<workers> workers { get; set; }
    }
}
