//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorKeeperRoom.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class workers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public workers()
        {
            this.key_handing = new ObservableCollection<key_handing>();
        }
    
        public int id_worker { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string position { get; set; }
        public string department { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<key_handing> key_handing { get; set; }
    }
}
